name: EpicSpawners
description: EpicSpawners
version: ${version}
softdepend: [Holograms, HolographicDisplays, CMI, Vault, PlayerPoints, UltimateStacker, StackMob, SkyBlock, Towny, RedProtect, Kingdoms, PlotSquared, GriefPrevention, USkyBlock, ASkyBlock, WorldGuard, Factions, PlaceholderAPI, ShopGUIPlus, UltimateClaims, Lands, BentoBox]
main: com.songoda.epicspawners.EpicSpawners
author: songoda
api-version: 1.13
commands:
  es:
    description: I have no idea.
    default: true
    aliases: [EpicSpawners]
    usage: /<command> [reload]
  SpawnerStats:
    description: I have no idea.
    default: false
    usage: /<command> [reload]
  SpawnerShop:
    description: I have no idea.
    default: false
    usage: /<command> [reload]
